# generated by datamodel-codegen:
#   filename:  HdModel.json
#   timestamp: 2025-07-23T04:23:50+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class HdModel(BaseModel):
    Title: Optional[str]
    HD: Optional[str]
