# generated by datamodel-codegen:
#   filename:  LineSeriesDto.json
#   timestamp: 2025-08-10T05:25:00+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel


class LineSeriesDto(BaseModel):
    Title: Optional[str]
    Id: Optional[str]
    Lenght: int
    Points: Optional[List[Optional[Dict[str, Any]]]]
