# generated by datamodel-codegen:
#   filename:  OrderDto.json
#   timestamp: 2025-08-10T05:25:01+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class OrderDto(BaseModel):
    TotalQuantity: float
    FilledQuantity: float
    RemainingQuantity: float
    OrderTypeId: Optional[str]
    Price: float
    TriggerPrice: float
    TrailOffset: float
    Status: Optional[str]
    OriginalStatus: Optional[str]
    AverageFillPrice: float
    Title: Optional[str]
