# generated by datamodel-codegen:
#   filename:  OrderReqDto.json
#   timestamp: 2025-08-10T05:25:01+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class OrderReqDto(BaseModel):
    SymbolId: Optional[str]
    AccountId: Optional[str]
    IsLong: bool
    OrderTypeId: Optional[str]
    Quantity: float
    Price: float
    TriggerPrice: float
    TrailOffset: float
    PositionId: Optional[str]
    StopLoss: float
    TakeProfit: float
    Comment: Optional[str]
    Title: Optional[str]
