# generated by datamodel-codegen:
#   filename:  PositionDto.json
#   timestamp: 2025-08-10T05:25:01+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel


class PositionDto(BaseModel):
    Title: Optional[str]
    Quantity: float
    OpenPrice: float
    OpenTime: datetime
    GrossPnL: float
    NetPnL: float
    Fee: float
    CurrentPrice: float
    StopLossId: Optional[str]
    TakeProfitId: Optional[str]
    GrossPnLTicks: float
