# generated by datamodel-codegen:
#   filename:  Test.json
#   timestamp: 2025-07-31T18:35:27+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Test(BaseModel):
    Title: Optional[str]
    Intero: int
