# generated by datamodel-codegen:
#   filename:  TestTre.json
#   timestamp: 2025-07-23T04:23:50+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class TestTre(BaseModel):
    Title: Optional[str]
    your_bool_prop: bool
    your_string_prop: Optional[str]
