# generated by datamodel-codegen:
#   filename:  TfExport.json
#   timestamp: 2025-07-23T04:23:50+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class TfExport(BaseModel):
    Title: Optional[str]
    IsActive: bool
